"use client";
import { Inter } from "next/font/google";
import Footer from "./_components/Footer";
import Header from "./_components/Header";
import "./globals.css";
import { StoreProvider } from "@/lib/redux/StoreProvider";
import Scroll from "./_components/Scroll";
import { usePathname } from "next/navigation";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "LifeStyle Mag",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const footerRoutes = [
    "/",
    "/blogs",
    "/favorite",
    "/profile",
    "/auth",
    "/blogs/[id]",
  ];
  const pathname = usePathname();

  const show =
    footerRoutes.includes(pathname) || pathname.startsWith("/blogs/");

  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          {show && <Header />}
          {children}
          {show &&  <Footer />}
          <Scroll />
        </body>
      </html>
    </StoreProvider>
  );
}
